favicon:
	inkscape --export-area-page --export-width 16  --export-background-opacity=0 favicon.svg --export-png tmp-16.png
	inkscape --export-area-page --export-width 32  --export-background-opacity=0 favicon.svg --export-png tmp-32.png
	inkscape --export-area-page --export-width 64  --export-background-opacity=0 favicon.svg --export-png tmp-64.png
	inkscape --export-area-page --export-width 57  --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-57x57.png
	inkscape --export-area-page --export-width 60  --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-60x60.png
	inkscape --export-area-page --export-width 72  --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-72x72.png
	inkscape --export-area-page --export-width 76  --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-76x76.png
	inkscape --export-area-page --export-width 114 --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-114x114.png
	inkscape --export-area-page --export-width 120 --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-120x120.png
	inkscape --export-area-page --export-width 144 --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-144x144.png
	inkscape --export-area-page --export-width 152 --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-152x152.png
	inkscape --export-area-page --export-width 180 --export-background-opacity=0 favicon.svg --export-png apple-touch-icon-180x180.png
	inkscape --export-area-page --export-width 32  --export-background-opacity=0 favicon.svg --export-png favicon-32x32.png
	inkscape --export-area-page --export-width 192 --export-background-opacity=0 favicon.svg --export-png android-chrome-192x192.png
	inkscape --export-area-page --export-width 96  --export-background-opacity=0 favicon.svg --export-png favicon-96x96.png
	inkscape --export-area-page --export-width 16  --export-background-opacity=0 favicon.svg --export-png favicon-16x16.png
	inkscape --export-area-page --export-width 144 --export-background-opacity=0 favicon.svg --export-png mstile-144x144.png
	convert tmp-16.png tmp-32.png tmp-64.png favicon.ico
	rm tmp-*.png
	mv favicon.ico ../../
